version: '3.7'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgre
      POSTGRES_USER: postgres
      POSTGRES_DB: crewsakan
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    ports:
      - "7000:8000"
volumes:
  postgres_data:
